
name: Deploy Groningen

on: 
  push:
    branches: [master]
    paths:
      - ".github/workflows/deploy.yml"
      - "data/*"
  workflow_run:
    workflows: ["Update Groningen data"]
    branches: [master]
    types: 
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'openknowledgebe/equalstreetnames'
          persist-credentials: false
      - uses: actions/checkout@v2
        with:
          path: 'cities/groningen'

      - name: Install and Build
        run: |
          npm install
          npm run build:groningen
        env:
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: 'dist/groningen' # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
